site_name: CAIXA Tem

theme:
  name: material
  language: pt
  font:
    text: 'Kurale'
  logo: assets/Images/logo.png
  favicon: assets/Images/icon2.png

docs_dir: docs/

extra_css:
  - assets/ExtraCss/page.css

nav:
  - Sobre: index.md
  - Planejamento: planejamento.md
  - Atas de reunião:
    - Ata 01: 'Atas/Ata01.md'
    - Ata 02: 'Atas/Ata02.md'
    - Ata 03: 'Atas/Ata03.md'
    - Ata 03.1: 'Atas/Ata03.1.md'
    - Ata 04: 'Atas/Ata04.md'
    - Ata 05: 'Atas/Ata05.md'
  - Apresentaçōes:
    - Apresentação 1: 'Apresentacao/apresentacao1.md'
    - Apresentação 2: 'Apresentacao/apresentacao2.md'
    - Apresentação 3: 'Apresentacao/apresentacao3.md'
  - Pré-rastreabilidade:
    - Rich pictures: 'PreRastreabilidade/rich_pictures.md'
  - Elicitação:
    - Técnicas de Elicitação:
      - Análise de Documentos: 'Elicitacao/Tecnicas/AnalisedeDocumentos.md'
      - Questionário: 'Elicitacao/Tecnicas/questionario.md'
      - Entrevista: 'Elicitacao/Tecnicas/entrevista.md'
      - Instrospecção: 'Elicitacao/Tecnicas/inpeccao.md'
      - Storytelling: 'Elicitacao/Tecnicas/storytelling.md'
      - Brainstorming: 'Elicitacao/Tecnicas/brainstorm.md'
      - Observação: 'Elicitacao/Tecnicas/observacao.md'
    - Técnicas de Priorização:
      - MoSCoW: 'Elicitacao/Priorizacao/moscow.md'
      - Gráfico Tempo X Esforço: 'Elicitacao/Priorizacao/esforcoImpacto.md'
    - Resultado: 'Elicitacao/Resultado.md'
  - Modelagem:
    - Cenários: 'Modelagem/Cenarios.md'
    - Léxicos: 'Modelagem/Lexicos.md'
    - Casos de Uso: 'Modelagem/CasoUso.md'
    - Especificação Suplementar: 'Modelagem/Especificacao.md'
    - NFR Framework: 'Modelagem/NFR_Framework.md'
    - Ágil:
      - Backlog do Produto: 'Modelagem/Agil/backlog.md'
      - História dos Usuários: 
        - US01 : Modelagem/Agil/Historia/US01.md'

