site_name: CAIXA Tem

theme:
  name: material
  language: pt
  font:
    text: 'Kurale'
  logo: assets/Images/logo.png
  favicon: assets/Images/icon2.png

docs_dir: docs/

extra_css:
  - assets/ExtraCss/page.css

nav:
  - Sobre: index.md
  - Planejamento: planejamento.md
  - Atas de reunião:
    - Ata 01: 'Atas/Ata01.md'
    - Ata 02: 'Atas/Ata02.md'
    - Ata 03: 'Atas/Ata03.md'
    - Ata 03.1: 'Atas/Ata03.1.md'
    - Ata 04: 'Atas/Ata04.md'
    - Ata 05: 'Atas/Ata05.md'
    - Ata 06: 'Atas/Ata06.md'
    - Ata 07: 'Atas/Ata07.md'
    - Ata 08: 'Atas/Ata08.md'
  - Apresentaçōes:
    - Apresentação 1: 'Apresentacao/apresentacao1.md'
    - Apresentação 2: 'Apresentacao/apresentacao2.md'
    - Apresentação 3: 'Apresentacao/apresentacao3.md'
    - Apresentação 4: 'Apresentacao/apresentacao4.md'
    - Apresentação 5: 'Apresentacao/apresentacao5.md'
    - Apresentação 6: 'Apresentacao/apresentacao6.md'
  - Pré-rastreabilidade:
    - Rich pictures: 'PreRastreabilidade/rich_pictures.md'
  - Elicitação:
    - Técnicas de Elicitação:
      - Análise de Documentos: 'Elicitacao/Tecnicas/AnalisedeDocumentos.md'
      - Questionário: 'Elicitacao/Tecnicas/questionario.md'
      - Entrevista: 'Elicitacao/Tecnicas/entrevista.md'
      - Instrospecção: 'Elicitacao/Tecnicas/inpeccao.md'
      - Storytelling: 'Elicitacao/Tecnicas/storytelling.md'
      - Brainstorming: 'Elicitacao/Tecnicas/brainstorm.md'
      - Observação: 'Elicitacao/Tecnicas/observacao.md'
    - Técnicas de Priorização:
      - MoSCoW: 'Elicitacao/Priorizacao/moscow.md'
      - Gráfico Tempo X Esforço: 'Elicitacao/Priorizacao/esforcoImpacto.md'
    - Resultado: 'Elicitacao/Resultado.md'
  - Modelagem:
    - Cenários: 'Modelagem/Cenarios.md'
    - Léxicos: 'Modelagem/Lexicos.md'
    - Casos de Uso: 'Modelagem/CasoUso.md'
    - Especificação Suplementar: 'Modelagem/Especificacao.md'
    - NFR Framework: 'Modelagem/NFR_Framework.md'
    - Ágil:
      - Backlog do Produto: 'Modelagem/Agil/backlog.md'
      - História dos Usuários: 
        - US01 : 'Modelagem/Agil/Historia/US01.md'
        - US02 : 'Modelagem/Agil/Historia/US02.md'
        - US03 : 'Modelagem/Agil/Historia/US03.md'
        - US04 : 'Modelagem/Agil/Historia/US04.md'
        - US05 : 'Modelagem/Agil/Historia/US05.md'
        - US06 : 'Modelagem/Agil/Historia/US06.md'
        - US07 : 'Modelagem/Agil/Historia/US07.md'
        - US08 : 'Modelagem/Agil/Historia/US08.md'
        - US09 : 'Modelagem/Agil/Historia/US09.md'
        - US010 : 'Modelagem/Agil/Historia/US010.md'
        - US011 : 'Modelagem/Agil/Historia/US011.md'
        - US012 : 'Modelagem/Agil/Historia/US012.md'
        - US013 : 'Modelagem/Agil/Historia/US013.md'
        - US014 : 'Modelagem/Agil/Historia/US014.md'
        - US015 : 'Modelagem/Agil/Historia/US015.md'
        - US016 : 'Modelagem/Agil/Historia/US016.md'
        - US017 : 'Modelagem/Agil/Historia/US017.md'
        - US018 : 'Modelagem/Agil/Historia/US018.md'
        - US019 : 'Modelagem/Agil/Historia/US019.md'
        - US020 : 'Modelagem/Agil/Historia/US020.md'
        - US021 : 'Modelagem/Agil/Historia/US021.md'
        - US022 : 'Modelagem/Agil/Historia/US022.md'
        - US023 : 'Modelagem/Agil/Historia/US023.md'
        - US024 : 'Modelagem/Agil/Historia/US024.md'
  - Análise:
    - Verificação:
      - Introdução: 'Analise/Analise_modelo.md'
      - Pré-rastreabilidade:
        - RichPicture: 'Analise/Analise_RichPicture.md'
      - Elicitação:
        - Técnicas de Elicitação:
          - Brainstorming: 'Analise/Analise_Brainstorming.md'
          - Entrevista: 'Analise/Analise_Entrvista.md'
          - StoryTelling: 'Analise/Analise_StoryTelling.md'
          - Observação: 'Analise/Analise_Observacao.md'
          - Questionário: 'Analise/Analise_Questionario.md'
          - Instrospecção: 'Analise/Analise_Instrospeccao.md'
        - Técnicas de Priorização:
          - Moscow: 'Analise/Analise_Moscow.md'
          - Gráfico esforço tempo: 'Analise/Analise_esforco_tempo.md'
      - Modelagem:
        - Caso de Uso: 'Analise/Analise_Caso_de_Uso.md'
        - Cenários: 'Analise/Analise_Cenarios.md'
        - Especificação Suplementar: 'Analise/Analise_Suplementar.md' 
        - Lexicos: 'Analise/Analise_Lexicos.md'
        - NFR: 'Analise/Analise_NFR.md'
        - Ágil:
          - Backlog: 'Analise/Analise_backlog.md'
    - Validação:
      - Validação Informal: 'Analise/Analise_Validacao_informal.md'
      - Prototipagem: 'Analise/Analise_prototipagem.md' 
  - Pós-rastreabilidade:
    - Matriz Forward-From: 'PosRastreabilidade/ForwardFrom.md'     
    - Matriz Backward-From: 'PosRastreabilidade/BackwardFrom.md'     
      
     
    
      

