site_name: CAIXA Tem

theme:
  name: material
  language: pt
  font:
    text: 'Kurale'
  logo: assets/Images/logo.png
  favicon: assets/Images/icon2.png

docs_dir: docs/

extra_css:
  - assets/ExtraCss/page.css

nav:
  - Sobre: index.md
  - Planejamento: planejamento.md
  - Atas de reunião:
    - Ata 01: 'Atas/Ata01.md'
  - Apresentaçōes:
    - Apresentação 1: 'Apresentacao/apresentacao1.md'
  - Pré-rastreabilidade:
    - Rich pictures: 'PreRastreabilidade/rich_pictures.md'
