site_name: Caixa Tem

theme:
  name: material
  language: pt

docs_dir: docs/

nav:
  - Sobre: index.md
  - Planejamento: planejamento.md
  - Atas de reunião:
    - Ata 01: 'Atas/Ata01.md'
  - Apresentaçōes:
    - Apresentação 1: 'Apresentacao/apresentacao1.md'
  - Pré-rastreabilidade:
    - Rich pictures: 'PreRastreabilidade/rich_pictures.md'
  - Elicitação:
    - Análise de Documentos: 'Elicitacao/AnalisedeDocumentos.md'
    - Questionario: 'Elicitacao/questionario.md'
    - Priorização:
      - MoSCoW: 'Elicitacao/Priorizacao/moscow.md'
      - Gráfico Tempo X Esforço: 'Elicitacao/Priorizacao/esforcoImpacto.md'
    - Resultado: 'Elicitacao/Elicitacao.md'
